class CreateSqlQueries:
    staging_events_table_create= ("""
        CREATE TABLE IF NOT EXISTS staging_events(
            artist text,
            auth text,
            firstname text,
            gender text,
            iteminsession INTEGER NOT NULL,
            lastname text,
            length text,
            level text,
            location text,
            method text,
            page text,
            registration text,
            sessionid INTEGER NOT NULL,
            song text,
            status INTEGER,
            ts bigint,
            useragent text,
            userid INTEGER  
        )
    """)

    staging_songs_table_create = ("""
        CREATE TABLE IF NOT EXISTS staging_songs(
            artist_id text,
            artist_latitude text,
            artist_location text,
            artist_longitude text,
            artist_name text,
            duration float,
            num_songs INTEGER,
            song_id text,
            title text,
            year INTEGER
        ) 
    """)

    user_table_create = ("""
        CREATE TABLE IF NOT EXISTS dimUsers(
            user_id INTEGER PRIMARY KEY sortkey,
            first_name text,
            last_name text,
            gender text,
            level text
        ) diststyle all
    """)

    song_table_create = ("""
        CREATE TABLE IF NOT EXISTS dimSongs(
            song_id text PRIMARY KEY sortkey,
            title text,
            artist_id text,
            year INTEGER,
            duration float
        ) diststyle all
    """)

    artist_table_create = ("""
        CREATE TABLE IF NOT EXISTS dimArtists(
            artist_id text NOT NULL PRIMARY KEY sortkey,
            name text,
            location text,
            latitude text,
            longitude text
        ) diststyle all
    """)

    time_table_create = ("""
        CREATE TABLE IF NOT EXISTS dimTime(
            start_time TIMESTAMP PRIMARY KEY sortkey,
            hour INTEGER,
            day INTEGER,
            week INTEGER,
            month INTEGER,
            year INTEGER,
            weekday INTEGER
        ) diststyle all
    """)

    songplay_table_create = ("""
        CREATE TABLE IF NOT EXISTS factSongPlays(
            songplay_id bigint GENERATED BY DEFAULT AS IDENTITY(0,1) PRIMARY KEY,
            start_time TIMESTAMP NOT NULL REFERENCES dimTime(start_time),
            user_id INTEGER NOT NULL REFERENCES dimUsers(user_id) distkey,
            level text,
            song_id text REFERENCES dimSongs(song_id) sortkey,
            artist_id text REFERENCES dimArtists(artist_id),
            session_id INTEGER NOT NULL,
            location text,
            user_agent text
        )
    """)

